### ISSUE TITLE
英伟达驱动无法安装

### ISSUE THREAD

**Issue by YidaozhanYa** [antman666/linux-xanmod-tt-uksm-cjktty#3]
[make.log](https://github.com/antman666/linux-xanmod-tt-uksm-cjktty/files/8606589/make.log)
这是 dkms 日志

**Comment by antman666** [comment]
啊这，检查一下有没有安装lld，log里面写到没有找到lld

**Comment by antman666** [comment]
检查一下lld是否正常🤔

**Comment by YidaozhanYa** [comment]
装了 llvm 和 lld 之后可以了，感谢～
