### ISSUE TITLE
can you update this PKGBUILD ？

### ISSUE THREAD

**Issue by cookieiz** [antman666/linux-xanmod-tt-uksm-cjktty#4]
How can I found patch-6.3.x-xanmod1-tt.zst

**Comment by antman666** [comment]
Here👇
https://github.com/antman666/linux-xanmod-tt-uksm-cjktty/releases/tag/linux-xanmod-tt_patch

**Comment by cookieiz** [comment]
How should I use subsequent versions of 6.3.4, such as 6.3.5, 6.3.8? Your Release only has 6.3.0 and 6.3.4

**Comment by cookieiz** [comment]
Your Release only has 6.3.0 and 6.3.4, can I compile version 6.3.8 with a patch of version 6.3.4?

**Comment by antman666** [comment]
The answer is no😂
I'll update it tomorrow😉

**Comment by cookieiz** [comment]
Can you provide a way to compile patches, write a markdown?

**Comment by cookieiz** [comment]
In addition to stable there is also the LTS version, the current version number is 6.1.34, it is better to provide a way to make patches

**Comment by antman666** [comment]
Already updated

**Comment by cookieiz** [comment]
Thanks
